

target ‘BAFParking’ do
 pod 'AFNetworking', '~> 3.1.0'
 pod 'DCIntrospect-ARC', '~> 0.0.8'
 pod 'SAMKeychain', '~> 1.5.2'
 pod 'MMDrawerController', '~> 0.6.0'
 pod 'IQKeyboardManager', '~> 4.0.9'
 pod 'MBProgressHUD', '~> 1.0.0'
 pod 'SDWebImage', '~> 4.0.0'
 pod 'MBProgressHUD', '~> 1.0.0'
 pod 'BaiduMapKit'
 pod 'WechatOpenSDK'
end
